name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      continue-on-error: false

    - name: Build application
      run: npm run electron:build
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: false

    - name: Verify build artifacts
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          ls -la release/*.exe || exit 1
        elif [ "${{ matrix.os }}" = "macos-latest" ]; then
          ls -la release/*.dmg || exit 1
        else
          ls -la release/*.AppImage || exit 1
        fi
      continue-on-error: false

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: singbox-configurator-${{ matrix.os }}
        path: release/
        if-no-files-found: error 