name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      continue-on-error: false

    - name: Build application
      run: npm run electron:build
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: false

    - name: Verify build artifacts
      run: |
        echo "Checking for Windows installer..."
        ls -la release/*.exe || echo "Windows installer not found"
        echo "Checking for Linux installer..."
        ls -la release/*.AppImage || echo "Linux installer not found"
        echo "Checking for macOS installer..."
        ls -la release/*.dmg || echo "macOS installer not found"
      continue-on-error: true

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release/*.exe
          release/*.AppImage
          release/*.dmg
        generate_release_notes: true
        fail_on_unmatched_files: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 